name: BLINK
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.0+1
  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2+1
  curved_navigation_bar: ^0.3.2
  fancy_bottom_navigation: ^0.1.0
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic

  assets:
    - assets/icon/award.png
    - assets/icon/book.png
    - assets/icon/broken-heart.png
    - assets/icon/folder.png
    - assets/icon/gallery.png
    - assets/icon/heart.png
    - assets/icon/image.png
    - assets/icon/laurel.png
    - assets/icon/member.png
    - assets/icon/music.png
    - assets/icon/music-note.png
    - assets/icon/open-book.png
    - assets/icon/S-book.png
    - assets/icon/S-broken-heart.png
    - assets/icon/S-gallery.png
    - assets/icon/S-laurel.png
    - assets/icon/S-music.png
